---
title: "Discrete Events Simulation for Covid-19 Recovery scheduling"
description: |
  A introduction to Descrete Events Simulations (DES) in healthcare with an overview of the use of DES for modelling outpatient services appointments at Providence Healthcare.  With the Covid-19 lockdown, there was a large backlog of appointments that needed to be filled.  Providence Outpatient Services explored the use of DES to evaluate increasing Staffing numbers, changing clinic hours and booking more appointments while maintaining social distancing requirements in their clinical and waiting areas.
  
author:
  - name: Kevin Wang, Neil Mistry
    url: https://www.linkedin.com/in/mingkun-wang/, https://www.linkedin.com/in/neilmistry/
date: 2022-09-23
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Discrete Events Simulation at Providence Outpatient Care & Services Covid-19 Recovery scheduling

## Intro

Discrete Events Simulations (DES) are stochastic models which allow us to simulate a real world system or process.  It is modelled by a system as a sequence of events in time.  Each event occurs at a particular instant in time and marks a change of state in the system, e.g. An arrival of a patient, or the delivery of a container of parts.  
This type of model is particularly useful in simulating queues or systems which have a sequence of steps (particularly manufacturing, call centers or healthcare).  Because queuing models become increasingly complex to solve, as we increase the number of nodes, DES may be the only solution to model these systems.  DES can be modelled with simple routing rules and probabilities of events occurring.  E.g. You don't know exactly when the next patient will arrive to the ED, what kind of symptoms or conditions they may display, and what kind of treatment they would need.

These simulations are can be used to test hypothetical changes in the system.  For instance, say you wish to add an 


act to customer wait times?  Is it worth the additional staffing cost?  What if we only added this teller during peak customer times?  What is the cost to benefit then?
DES has long been proven successful in manufacturing, services, and supply chain sectors in solving complex resourcing and efficiency questions.  With growing concern on increasing costs to provide healthcare, and perceived lack of efficiency, there is growing usage of DES in healthcare.
DES is commonly used to test schedules (for operating rooms, nursing, emergency department staffing, or other resourcing), test equipment purchase decisions (how many IV pumps are required to provide full coverage to the hospital?), space requirements (how many patient rooms, waiting chairs, do we need in this ED?) and even managing patient admissions and scheduling procedures.

At Providence, with the second Covid-19 pandemic dwindling, we wanted to test schedules to cut down the growing backlog of outpatient appointments required to fill while ensuring safe social distancing practices within the hospital.


## Background

The Providence Healthcare Center(PHC) Outpatient Service Department consists of multiple clinics providing medical appointments.  Each patient arrives, registers, and wait for the appointment in the waiting areas or vehicle.  They will then be escorted to clinical waiting areas or directed into a room.  After the appointment, they may continue to wait in the clinical waiting areas for follow ups or leave the hospital.  During this process, there may be congestion resulting from a combinations of patient behaviors, system resource and capacity (early-arrival of wheel-trans patients, max room capacity, lack of therapists); A smooth outpatient process is important for the hospital system to run efficiently for optimal patient care and quality of service.

< Insert flow diagram here >

Under COVID regulations, all individuals are required to maintain social distancing between each other.  To follow the regulation and minimize unnecessary contacts, the Outpatient Service Department needs to control the maximum number of patients in each area of the department.  
Planning to reopen more outpatient services (and to reduce the backlog created by shutdowns during the first two waves of the pandemic), the outpatient department wants to test adding additional appointments to their schedule with a combination of more staffing, longer hours, more patients and additional working days, while maintaining social distancing requirements.  

## Solution

The solution that was deployed for the PHC Outpatient Service Department consists of two parts:

1) A simulation model that helps recreate the physical space capacity and analyze the system & process performance

2) designing a web user interface that requires users to input key features of the simulation for testing different scenarios. In addition, the model would output key performance indicators to help access the performance of the proposed plans/system. 


## Methodologies
The simulation model is constructed using Python. ‘SimPy’ is used as the essential library to construct the simulation model, along with Pandas and NumPy to help with the data science portion of the model. The python model mainly consists of three parts:

- A defined object class called “Patient” with all necessary attributes and pre-defined calculation functions for results and outputs. Attributes include but not limit to: Patient index, appointment type, appointment clinic, wheel-trans probability, etc.

- The second part consists of logging, status update, capacity checking and calculation functions for the simulation process. Some of the process Detailed information of patient arrivals are calculated and recorded through these supporting functions.

- The last part is the simulation model function, where it reads in user defined clinics’ capacity, registration time, and input data excel file. The model then reads the patient schedules and generates patients based on their scheduled appointment time. 


### simulated outpatient process

- INITIALIZATION: Patients have two types, virtual or in-person. Virtual patients can escape all the registration steps, directly start their therapy appointment if available and leave immediately after appointment. In-person patients would just simply follow the normal outpatient process. 
- ARRIVAL: The simulated in-person patients would arrive to the registration desk, either on their own or by wheel-trans. Their arrival type is determined based on the wheel-trans arrival probability and python randomizer. In the registration wait room, if there is enough space to allow new patients in, new patients can then get registered; else new patients would have to wait for new capacity coming up to enter the registration room.
- THERAPY: Once patients get registered, a schedule check would occur to see if the room and therapist booked for this patient(s) are available. If available, status would be updated, and patients can proceed to their appointments immediately. If not, patients would have to wait until the clinic/therapist is ready.
- DIMISSAL: During dismissal, the arrival type is first checked. If the patient arrived by wheel-trans, then the registration wait room capacity would be checked to see if there is any space available for the leaving patients. If yes, wheel-trans patients can wait till their wheel-trans service arrive. If not, they will have to wait in the clinic wait rooms for an upcoming space. If the patient arrived on their own, they could leave immediately after their appointment. Status of current room capacities would be updated accordingly. 

•	During this, process, all related/interested performance stats (wait time, current number in system) are recorded for result calculations. Utilization plots for clinics/therapists are also plotted for easier understanding. 
Limitations:
The simulation model itself basically replicates the normal outpatient service process but simplifies it by ignoring some of the variabilities in process times due to the lack of data. Instead of fitting a time distribution, we had to use a more deterministic approach by assuming a static service time for all the servicing times involved in the model. However, once enough data is collected, those distributions can be obtained by data-fitting and directly apply to the model. In this way, the model would have more randomness, and thus more realistic comparing to real life.

## Evaluations

## Summary

We implemented an analytical solution in Python to address the capacity planning problem for the PHC Outpatient Service Department using DES. The tool models the real-life outpatient process and helps the Outpatient service teams to assess their system process performances and provide insights on underperforming for optimal patient care and improved quality of service.  The current model still has some limitations due to the lack of data, but can be addressed and improved in the future.

