variables:
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/renv/cache

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    
image:
  name: rocker/tidyverse:4.2.2

before_script:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

stages:
  - execute_r_script
  - commit_new_files

execute_r_script:
  stage: execute_r_script
  script:
    - Rscript clean.R  # Run the R script
  only: 
    - gitlab-ci-test
    
commit_new_files:
  stage: commit_new_files
  script:
    - git config user.name "DSAA Blog"
    - git config user.email "noreply-dsaa@unityhealth.to"
    - git add .
    - git commit -m "Prepare blog for production [skip ci]"
    - git push HEAD:$CI_COMMIT_REF_NAME

