variables:
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/renv/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library
  GIT_STRATEGY: clone

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}
    
image:
  name: rocker/tidyverse:4.2.2

stages:
  - add_file_test
  
add_file:
  stage: add_file_test
  script:
    - touch example.txt
    - date +'%Y-%m-%d' > example.txt 
    - git config user.name "DSAA Blog"
    - git config user.email "noreply-dsaa@unityhealth.to"
    - git add example.txt
    - git commit -m "Add example.txt from $CI_COMMIT_SHORT_SHA [skip ci]" 
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_REF_NAME 
    


