variables:
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/renv/cache

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    
image:
  name: rocker/tidyverse

before_script:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

stages:
  - execute_r_script

execute_r_script:
  stage: execute_r_script
  script:
    - Rscript clean.R  # Run the R script
  only: 
    - gitlab-ci-test

